Repository appuniversum/ember-appuniversum, pull requests merged in 2022-06, with the labels that each got.

#270 Rework pill component action
  addon/components/au-pill.hbs
  addon/components/au-pill.js
  stories/4-components/Notifications/AuPill.stories.js
  tests/integration/components/au-pill-test.js
Labels: bug

#271 Use hand cursor for actions
  addon/components/au-file-card.hbs
  addon/components/au-time-picker.hbs
  app/styles/ember-appuniversum/_c-alert.scss
  app/styles/ember-appuniversum/_c-button.scss
  app/styles/ember-appuniversum/_c-dropdown.scss
  app/styles/ember-appuniversum/_c-file-card.scss
  app/styles/ember-appuniversum/_c-file-upload.scss
  app/styles/ember-appuniversum/_c-modal.scss
  app/styles/ember-appuniversum/_c-pill.scss
  app/styles/ember-appuniversum/_c-timepicker.scss
Labels: bug

#274 Apply modal fix
  addon/components/au-modal.hbs
  addon/components/au-modal.js
Labels: bug

#276 AuModal improvements
  addon/components/au-modal.hbs
  addon/components/au-modal.js
  tests/integration/components/au-modal-test.js
Labels: internal

#277 Regulatory statement additions
  app/styles/ember-appuniversum/_c-list.scss
  package-lock.json
  public/icons/bookmark.svg
  public/icons/nav-down-double.svg
  public/icons/nav-up-double.svg
  stories/6-templates/AppEditor.stories.js
  stories/assets/icons.js
  tests/dummy/app/components/au-icon-list.js
  tests/dummy/app/styles/_d-editor-chrome.scss
  tests/dummy/app/styles/_d-editor-mockup.scss
Labels: enhancement

#279 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/chromatic.yml
  CONTRIBUTING.md
  README.md
Labels: internal

#275 Upgrade storybook
  package-lock.json
  package.json
Labels: internal

#281 Make tabs border color consistent with toolbar, fixes #278
  app/styles/ember-appuniversum/_c-tabs.scss
Labels: bug

#283 Fix a problem where selecting a PowerSelect option closes the modal
  addon/components/au-modal.hbs
  addon/components/au-modal.js
  tests/integration/components/au-modal-test.js
Labels: bug

#287 Rework loader, fixes #286
  addon/components/au-loader.hbs
  addon/components/au-loader.js
  app/styles/ember-appuniversum/_c-loader.scss
  stories/4-components/Notifications/AuLoader.stories.js
Labels: enhancement

#288 Use global divider variable
  .storybook/preview.js
  app/styles/ember-appuniversum/_c-accordion.scss
  app/styles/ember-appuniversum/_c-dropdown.scss
  app/styles/ember-appuniversum/_c-list-navigation.scss
  app/styles/ember-appuniversum/_c-list.scss
  app/styles/ember-appuniversum/_c-main-footer.scss
  app/styles/ember-appuniversum/_c-pagination.scss
  app/styles/ember-appuniversum/_c-sidebar-action.scss
  app/styles/ember-appuniversum/_c-table.scss
  app/styles/ember-appuniversum/_c-tabs.scss
  app/styles/ember-appuniversum/_c-toolbar.scss
  app/styles/ember-appuniversum/_p-ember-power-select.scss
  package-lock.json
  package.json
  stories/2-variables/Colors.stories.mdx
  stories/2-variables/CssVariables.stories.mdx
  stories/2-variables/SassVariables.stories.mdx
  stories/2-variables/Semantic-colors.stories.mdx
Labels: internal
