Repository appuniversum/ember-appuniversum, pull requests merged in 2022-05, with the labels that each got.

#244 Fix rendering of list component inside content component
  app/styles/ember-appuniversum/_c-content.scss
Labels: bug

#245 fixes #242
  app/styles/ember-appuniversum/_p-ember-power-select.scss
Labels: bug

#246 fixes #240
  addon/components/au-link.js
Labels: bug

#249 `AuTimepicker` fixes
  addon/components/au-time-picker.hbs
  addon/components/au-time-picker.js
Labels: bug

#252 AuTimepicker remake
  addon/components/au-time-picker.hbs
  addon/components/au-time-picker.js
  addon/helpers/format-time-digit.js
  app/helpers/format-time-digit.js
  package-lock.json
  package.json
  tests/integration/components/au-time-picker-test.js
  tests/integration/helpers/format-time-test.js
Labels: enhancement

#257 Move tracked-toolbox to the dependencies list
  package-lock.json
  package.json
Labels: bug

#260 Fix power select padding and line height
  app/styles/ember-appuniversum/_p-ember-power-select.scss
Labels: bug

#259 Update the `AuButton` component so it matches the latest Webuniversum version
  addon/components/au-button.hbs
  addon/components/au-button.js
  addon/components/au-link.js
  app/styles/ember-appuniversum/_c-button.scss
  stories/4-components/Buttons/AuButton.stories.js
  stories/4-components/Links/AuLink.stories.js
  stories/4-components/Links/AuLinkExternal.stories.js
Labels: enhancement

#253 yield the `AuToolbarGroup` component from the `AuToolbar` component
  addon/components/au-accordion.hbs
  addon/components/au-toolbar-group.js
  addon/components/au-toolbar.hbs
  stories/4-components/Content/AuCard.stories.js
  stories/4-components/Layout/AuToolbar.stories.js
  stories/4-components/Tables/AuDataTable.stories.js
  stories/6-templates/AppBreadcrumbs.stories.js
  stories/6-templates/AppEditor.stories.js
  tests/helpers/deprecations.js
  tests/integration/components/au-alert-test.js
  tests/integration/components/au-toolbar-group-test.js
  tests/integration/components/au-toolbar-test.js
Labels: enhancement

#264 Add agenda icons
  public/icons/bold.svg
  public/icons/caret-up-down.svg
  public/icons/eye.svg
  public/icons/html-dot.svg
  public/icons/indent.svg
  public/icons/italic.svg
  public/icons/link-broken.svg
  public/icons/reverse-indent.svg
  public/icons/strikethrough.svg
  public/icons/table-column-end-add.svg
  public/icons/table-column-remove.svg
  public/icons/table-column-start-add.svg
  public/icons/table-insert.svg
  public/icons/table-row-end-add.svg
  public/icons/table-row-remove.svg
  public/icons/table-row-start-add.svg
  public/icons/table.svg
  public/icons/underlined.svg
  public/icons/users-four-of-four.svg
  public/icons/users-one-of-four.svg
  public/icons/users-single.svg
  public/icons/users-three-of-four.svg
  public/icons/users-two-of-four.svg
  public/icons/visible.svg
  public/icons/website.svg
  stories/assets/icons.js
  tests/dummy/app/components/au-icon-list.js
Labels: enhancement

#261 Tabs component
  addon/components/au-link.hbs
  addon/components/au-tabs.hbs
  addon/components/au-tabs/item.hbs
  app/components/au-tabs.js
  app/components/au-tabs/item.js
  app/styles/ember-appuniversum/_a-components.scss
  app/styles/ember-appuniversum/_c-link.scss
  app/styles/ember-appuniversum/_c-tabs.scss
  stories/1-outline/Getting-started.stories.mdx
  stories/4-components/Navigation/AuTabs.stories.js
  tests/integration/components/au-tabs-test.js
  tests/integration/components/au-tabs/item-test.js
Labels: enhancement

#266 Yield tabs item and list item
  addon/components/au-list.hbs
  addon/components/au-list/item.js
  addon/components/au-tabs.hbs
  stories/4-components/Content/AuList.stories.js
  stories/4-components/Navigation/AuTabs.stories.js
Labels: bug

#268 Replace `{{prop}}` with a custom modifier
  addon/components/au-date-picker.hbs
  addon/modifiers/au-props.js
  app/modifiers/au-props.js
  package.json
  tests/integration/modifiers/au-props-test.js
Labels: internal
