Repository appuniversum/ember-appuniversum, pull requests merged in 2022-08, with the labels that each got.

#299 Update ember-data-table to v2.1.0
  package-lock.json
  package.json
Labels: internal

#303 Fix `AuAlert` deprecations in the `AuFileUpload` component
  addon/components/au-file-upload.hbs
Labels: bug

#300 Toast/notification system
  addon/components/au-toaster.hbs
  addon/components/au-toaster.js
  addon/services/toaster.js
  app/components/au-toaster.js
  app/services/toaster.js
  app/styles/ember-appuniversum/_a-components.scss
  app/styles/ember-appuniversum/_c-toaster.scss
  stories/5-components/Notifications/AuToaster.stories.js
  tests/dummy/app/components/au-toast-demo.hbs
  tests/dummy/app/components/au-toast-demo.js
  tests/unit/services/toaster-test.js
Labels: enhancement

#307 Add support for ember-power-select v6
  package-lock.json
  package.json
Labels: enhancement

#305 Drop node 12 support
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#306 Remove support for Ember 3.20 and 3.24
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#312 Document button placement and best practices
  stories/6-patterns/buttons.stories.js
Labels: documentation

#315 Revert flex behaviour on AuBodyContainer component
  app/styles/ember-appuniversum/_c-body-container.scss
  app/styles/ember-appuniversum/_c-main-container.scss
  tests/dummy/app/styles/_d-component.scss
Labels: bug

#313 Various small improvements to button component
  addon/components/au-button.hbs
  addon/components/au-button.js
  app/styles/ember-appuniversum/_c-button.scss
  app/styles/ember-appuniversum/_c-icon.scss
  app/styles/ember-appuniversum/_s-root.scss
  stories/7-templates/AppLogin.stories.js
Labels: enhancement
