Repository appuniversum/ember-appuniversum, pull requests merged in 2022-09, with the labels that each got.

#302 ember-file-upload v5+ update
  addon/components/au-file-upload.hbs
  addon/components/au-file-upload.js
  package-lock.json
  package.json
  stories/5-components/Forms/AuFileUpload.stories.js
  tests/unit/utils/is-valid-file-type-test.js
Labels: breaking

#316 Panel component
  addon/components/au-panel.hbs
  addon/components/au-panel/section.hbs
  app/components/au-panel.js
  app/components/au-panel/section.js
  app/styles/ember-appuniversum/_a-components.scss
  app/styles/ember-appuniversum/_c-panel.scss
  stories/5-components/Content/AuPanel.stories.js
  tests/integration/components/au-panel-test.js
  tests/integration/components/au-panel/section-test.js
Labels: enhancement

#319 Spacing issue (icon + text) link component with button skin
  addon/components/au-file-card.hbs
  addon/components/au-link-external.hbs
  addon/components/au-link-external.js
  addon/components/au-link.hbs
  addon/components/au-link.js
  addon/components/au-main-header.hbs
  app/styles/ember-appuniversum/_c-link.scss
  stories/5-components/Links/AuLink.stories.js
  stories/7-templates/AppBreadcrumbs.stories.js
  stories/7-templates/AppEditor.stories.js
Labels: bug

#320 Fix power select multiple disabled state, #318
  app/styles/ember-appuniversum/_p-ember-power-select.scss
  stories/5-components/Forms/PowerSelect/MultipleSelect.stories.js
  stories/5-components/Forms/PowerSelect/SingleSelect.stories.js
Labels: bug

#304 Update to Ember 4.4 LTS
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  CONTRIBUTING.md
  README.md
  addon/components/au-card.hbs
  package-lock.json
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  tests/integration/components/au-app-test.js
  tests/integration/components/au-link-external-test.js
  tests/integration/components/au-modal-test.js
  tests/unit/helpers/au-link-to-models-test.js
Labels: internal

#323 Rework dropdown
  addon/components/au-dropdown.hbs
  addon/components/au-dropdown.js
  app/styles/ember-appuniversum/_c-button.scss
  app/styles/ember-appuniversum/_c-dropdown.scss
  app/styles/ember-appuniversum/_c-main-header.scss
  stories/5-components/Brand/AuMainHeader.stories.js
  stories/5-components/Navigation/AuDropdown.stories.js
  stories/7-templates/AppBreadcrumbs.stories.js
  stories/7-templates/AppEditor.stories.js
  stories/7-templates/AppSidebar.stories.js
  tests/integration/components/au-dropdown-test.js
Labels: enhancement

#325 Add wrap property to a button
  addon/components/au-button.hbs
  app/styles/ember-appuniversum/_c-button.scss
  stories/5-components/Buttons/AuButton.stories.js
Labels: enhancement
