Repository appuniversum/ember-appuniversum, pull requests merged in 2022-04, with the labels that each got.

#228 Dependency maintenance
  package-lock.json
  package.json
Labels: internal

#232 Feature/table icons
  public/icons/bold.svg
  public/icons/indent.svg
  public/icons/italic.svg
  public/icons/redo.svg
  public/icons/reverse-indent.svg
  public/icons/strikethrough.svg
  public/icons/table-column-end-add.svg
  public/icons/table-column-remove.svg
  public/icons/table-column-start-add.svg
  public/icons/table-insert.svg
  public/icons/table-row-end-add.svg
  public/icons/table-row-remove.svg
  public/icons/table-row-start-add.svg
  public/icons/table.svg
  public/icons/underlined.svg
  public/icons/undo.svg
  stories/assets/icons.js
  tests/dummy/app/components/au-icon-list.js
Labels: enhancement

#235 Extend accordion layout options
  addon/components/au-accordion.hbs
  addon/components/au-accordion.js
  app/styles/ember-appuniversum/_c-accordion.scss
  app/styles/ember-appuniversum/_c-button.scss
  stories/4-components/Content/AuAccordion.stories.js
Labels: enhancement

#230 Fix remaining deprecations triggered by ember-data-table
  addon/components/au-data-table/content-body.hbs
  addon/components/au-data-table/content-header.hbs
  addon/components/au-data-table/default-data-table-content-body.hbs
  addon/components/au-data-table/number-pagination.hbs
  stories/4-components/Tables/AuDataTable.stories.js
Labels: bug

#234 Remove the `on-click-inside` modifier
  addon/components/au-dropdown.hbs
  addon/modifiers/on-click-inside.js
  app/modifiers/on-click-inside.js
  package.json
  tests/integration/components/au-dropdown-test.js
  tests/integration/modifiers/on-click-inside-test.js
Labels: internal

#238 List component and accordion fix
  addon/components/au-list.hbs
  addon/components/au-list.js
  addon/components/au-list/item.hbs
  app/components/au-list.js
  app/components/au-list/item.js
  app/styles/ember-appuniversum/_a-components.scss
  app/styles/ember-appuniversum/_c-accordion.scss
  app/styles/ember-appuniversum/_c-list.scss
  stories/4-components/Content/AuList.stories.js
Labels: enhancement

#237 Deprecate the `alert` prefixed argument names of the `AuAlert` component
  addon/components/au-alert.hbs
  addon/components/au-alert.js
  stories/4-components/Notifications/AuAlert.stories.js
  tests/integration/components/au-alert-test.js
Labels: enhancement

#225 Add form patterns and missing form components
  addon/components/au-fieldset-content.hbs
  addon/components/au-fieldset-legend.hbs
  addon/components/au-fieldset-legend.js
  addon/components/au-fieldset.hbs
  addon/components/au-fieldset.js
  addon/components/au-form-row.hbs
  addon/components/au-form-row.js
  app/components/au-fieldset-content.js
  app/components/au-fieldset-legend.js
  app/components/au-fieldset.js
  app/components/au-form-row.js
  app/styles/ember-appuniversum/_a-components.scss
  app/styles/ember-appuniversum/_c-button-group.scss
  app/styles/ember-appuniversum/_c-content.scss
  app/styles/ember-appuniversum/_c-fieldset.scss
  app/styles/ember-appuniversum/_c-form-row.scss
  app/styles/ember-appuniversum/_c-help-text.scss
  app/styles/ember-appuniversum/_c-label.scss
  stories/1-outline/Getting-started.stories.mdx
  stories/4-components/Forms/AuFieldset.stories.js
  stories/4-components/Forms/AuFormRow.stories.js
  stories/5-patterns/forms.stories.js
  stories/6-templates/AppBreadcrumbs.stories.js
  stories/6-templates/AppEditor.stories.js
  stories/6-templates/AppLogin.stories.js
  stories/6-templates/AppSidebar.stories.js
Labels: enhancement

#239 Add alignment option for the datepicker
  addon/components/au-date-picker.hbs
  addon/components/au-date-picker.js
  app/styles/ember-appuniversum/_c-form-row.scss
  app/styles/ember-appuniversum/_p-duet-datepicker.scss
  stories/4-components/Forms/AuDatePicker.stories.js
Labels: enhancement
