Repository appuniversum/ember-appuniversum, pull requests merged in 2022-02, with the labels that each got.

#183 Upgrade appuniversum
  CHANGELOG.md
  addon/components/au-alert.js
  addon/components/au-content.js
  addon/components/au-heading.js
  addon/components/au-pill.hbs
  app/styles/ember-appuniversum.scss
  app/styles/ember-appuniversum/_c-alert.scss
  app/styles/ember-appuniversum/_c-badge.scss
  app/styles/ember-appuniversum/_c-brand.scss
  app/styles/ember-appuniversum/_c-button.scss
  app/styles/ember-appuniversum/_c-content-header.scss
  app/styles/ember-appuniversum/_c-content.scss
  app/styles/ember-appuniversum/_c-control.scss
  app/styles/ember-appuniversum/_c-data-table.scss
  app/styles/ember-appuniversum/_c-dropdown.scss
  app/styles/ember-appuniversum/_c-file-upload.scss
  app/styles/ember-appuniversum/_c-heading.scss
  app/styles/ember-appuniversum/_c-help-text.scss
  app/styles/ember-appuniversum/_c-input.scss
  app/styles/ember-appuniversum/_c-label.scss
  app/styles/ember-appuniversum/_c-link.scss
  app/styles/ember-appuniversum/_c-list-horizontal.scss
  app/styles/ember-appuniversum/_c-list-navigation.scss
  app/styles/ember-appuniversum/_c-main-header.scss
  app/styles/ember-appuniversum/_c-modal.scss
  app/styles/ember-appuniversum/_c-pagination.scss
  app/styles/ember-appuniversum/_c-pill.scss
  app/styles/ember-appuniversum/_c-sidebar.scss
  app/styles/ember-appuniversum/_c-table.scss
  app/styles/ember-appuniversum/_c-textarea.scss
  app/styles/ember-appuniversum/_c-timepicker.scss
  app/styles/ember-appuniversum/_c-toggle-switch.scss
  app/styles/ember-appuniversum/_c-toolbar.scss
  app/styles/ember-appuniversum/_p-duet-datepicker.scss
  app/styles/ember-appuniversum/_p-ember-power-select.scss
  package-lock.json
  package.json
  stories/1-outline/Accessibility.stories.mdx
  stories/1-outline/Getting-started.stories.mdx
  stories/2-foundation/Colors.stories.mdx
  stories/2-foundation/CssVariables.stories.mdx
  stories/2-foundation/SassVariables.stories.mdx
  stories/3-utilities/Backgrounds.stories.mdx
  stories/3-utilities/Flex.stories.mdx
  stories/3-utilities/Hide.stories.mdx
  stories/3-utilities/MaxWidths.stories.mdx
  stories/3-utilities/Print.stories.mdx
  stories/3-utilities/Spacing.stories.mdx
  stories/3-utilities/TextAlign.stories.mdx
  stories/3-utilities/Typography.stories.mdx
  stories/3-utilities/Visible.stories.mdx
  stories/3-utilities/Widths.stories.mdx
  stories/3-utilities/WordBreak.stories.mdx
  stories/4-components/Content/AuContent.stories.js
  stories/4-components/Content/AuHeading.stories.js
  stories/4-components/Content/AuHr.stories.js
  stories/Introduction.stories.mdx
  tests/dummy/app/styles/_d-editor-chrome.scss
  tests/dummy/app/styles/_d-editor-mockup.scss
  tests/dummy/app/styles/_d-swatch.scss
Labels: enhancement

#186 Fixes #184: The AuCard toggle button shrinks
  app/styles/ember-appuniversum/_c-card.scss
  stories/4-components/Content/AuCard.stories.js
Labels: bug

#197 Group scss imports
  app/styles/ember-appuniversum.scss
  app/styles/ember-appuniversum/_a-components.scss
  app/styles/ember-appuniversum/_a-elements.scss
  app/styles/ember-appuniversum/_a-generic.scss
  app/styles/ember-appuniversum/_a-objects.scss
  app/styles/ember-appuniversum/_a-plugins.scss
  app/styles/ember-appuniversum/_a-settings.scss
  app/styles/ember-appuniversum/_a-tools.scss
  app/styles/ember-appuniversum/_a-utilities.scss
  stories/1-outline/Getting-started.stories.mdx
Labels: internal

#198 Make input-wrapper adapt to the width of the input
  addon/components/au-input.hbs
  app/styles/ember-appuniversum/_c-input.scss
Labels: bug

#202 Bump ember-power-select
  package-lock.json
  package.json
Labels: internal

#199 Add named block support to the `AuModal` component
  addon/components/au-modal-body.hbs
  addon/components/au-modal-footer.hbs
  addon/components/au-modal.hbs
  stories/4-components/Content/AuModal.stories.js
  tests/integration/components/au-modal-test.js
Labels: enhancement

#206 Switch to the official Ember Github Actions config
  .github/workflows/ci.yml
  .travis.yml
  config/ember-try.js
Labels: internal
