Repository appuniversum/ember-appuniversum, pull requests merged in 2023-10, with the labels that each got.

#442 Update `tracked-toolbox` to v2
  package-lock.json
  package.json
Labels: enhancement

#445 Deprecate the `@size` argument for the `AuLoader` component
  addon/components/au-loader.gjs
  tests/integration/components/au-loader-test.js
Labels: enhancement, Deprecation

#447 Drop Ember 3.28 and 4.4 support
  .github/workflows/ci.yml
  README.md
  package.json
  tests/dummy/config/ember-try.js
Labels: breaking

#449 Add vote star filled icon
  public/icons/vote-star-filled.svg
  stories/assets/icons.js
  tests/dummy/app/components/au-icon-list.js
Labels: enhancement
