Repository appuniversum/ember-appuniversum, pull requests merged in 2023-01, with the labels that each got.

#344 Addition of floating UI helpers
  addon/private/modifiers/floating-ui.js
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
  tests/integration/private/modifiers/floating-ui-test.js
Labels: internal

#353 Addition of indeterminate state for the checkbox component
  addon/components/au-control-checkbox.hbs
  app/styles/ember-appuniversum/_c-control.scss
  stories/5-components/Forms/AuCheckbox.stories.js
Labels: enhancement

#352 Improvement of solo (label-less) control (checkbox & radio) components
  addon/components/au-control-checkbox.hbs
  addon/components/au-control-checkbox.js
  addon/components/au-control-radio.hbs
  addon/components/au-control-radio.js
  app/styles/ember-appuniversum/_c-control.scss
Labels: enhancement

#349 Application of floating UI helpers within dropdown component
  addon/components/au-dropdown.hbs
  addon/components/au-dropdown.js
  app/styles/ember-appuniversum/_c-dropdown.scss
  package-lock.json
  package.json
Labels: enhancement

#357 Au radio control checked should be without the @
  stories/5-components/Forms/AuFieldset.stories.js
  stories/5-components/Forms/AuRadio.stories.js
  stories/6-patterns/forms.stories.js
Labels: documentation

#360 Make the au-link-to-models helper truly private
  addon/components/au-link.hbs
  addon/components/au-link.js
  addon/components/au-navigation-link.hbs
  addon/components/au-navigation-link.js
  addon/components/au-pill.hbs
  addon/components/au-pill.js
  addon/private/helpers/link-to-models.js
  app/helpers/au-link-to-models.js
  tests/unit/helpers/au-link-to-models-test.js
Labels: internal

#361 Deprecate the `#ember-appuniversum-wormhole` element
  .storybook/preview-body.html
  addon/components/au-modal-container.hbs
  addon/components/au-modal.js
  app/components/au-modal-container.js
  ember-cli-build.js
  index.js
  stories/5-components/Content/AuModal.stories.js
  tests/integration/components/au-modal-container-test.js
  tests/integration/components/au-modal-test.js
Labels: enhancement

#362 Add an `@onClose` argument to the `AuDropdown` component
  addon/components/au-dropdown.js
  stories/5-components/Navigation/AuDropdown.stories.js
  tests/integration/components/au-dropdown-test.js
Labels: enhancement

#363 Add an `@onClose` argument to the `AuAlert` component
  addon/components/au-alert.js
  stories/5-components/Notifications/AuAlert.stories.js
  tests/integration/components/au-alert-test.js
Labels: enhancement
