Repository appuniversum/ember-appuniversum, pull requests merged in 2023-09, with the labels that each got.

#423 Clicking issue for wormhole elements/components within the modal component
  addon/components/au-modal.hbs
Labels: bug

#426 Ember v5.2 blueprint update
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .stylelintignore
  .stylelintrc.js
  .watchmanconfig
  addon/components/au-control-checkbox.js
  addon/components/au-control-radio.js
  addon/components/au-date-input.js
  addon/components/au-date-picker.js
  addon/components/au-dropdown.js
  addon/components/au-input.js
  addon/components/au-modal.js
  addon/components/au-toggle-switch.js
  addon/modifiers/au-props.js
  addon/private/helpers/link-to-models.js
  addon/private/modifiers/floating-ui.js
  app/styles/ember-appuniversum/_c-button.scss
  app/styles/ember-appuniversum/_c-card.scss
  app/styles/ember-appuniversum/_c-dropdown.scss
  app/styles/ember-appuniversum/_c-link.scss
  app/styles/ember-appuniversum/_c-list-navigation.scss
  app/styles/ember-appuniversum/_c-loader.scss
  app/styles/ember-appuniversum/_c-main-header.scss
  app/styles/ember-appuniversum/_c-modal.scss
  app/styles/ember-appuniversum/_c-sidebar-action.scss
  app/styles/ember-appuniversum/_c-toggle-switch.scss
  app/styles/ember-appuniversum/_g-font.scss
  app/styles/ember-appuniversum/_p-ember-power-select.scss
  app/styles/ember-appuniversum/_s-global.scss
  index.js
  package-lock.json
  package.json
  stories/2-variables/SassVariables.stories.mdx
  tests/dummy/app/components/au-toast-demo.js
  tests/dummy/app/index.html
  tests/dummy/app/styles/_d-editor-chrome.scss
  tests/dummy/app/styles/_d-editor-mockup.scss
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/deprecations.js
  tests/index.html
  tests/integration/components/au-checkbox-group-test.js
  tests/integration/components/au-date-input-test.js
  tests/integration/components/au-date-picker-test.js
  tests/integration/components/au-dropdown-test.js
  tests/integration/components/au-main-container-test.js
  tests/integration/components/au-modal-test.js
  tests/integration/components/au-radio-group-test.js
  tests/integration/components/au-radio-test.js
  tests/integration/components/au-time-picker-test.js
  tests/integration/components/au-toaster-test.js
  tests/integration/components/au-toggle-switch-test.js
  tests/integration/modifiers/au-props-test.js
Labels: internal

#427 Add Ember v5 support
  package.json
Labels: enhancement

#429 Deprecate some `AuInput` features
  addon/components/au-input.hbs
  addon/components/au-input.js
  stories/5-components/Forms/AuInput.stories.js
  stories/5-components/Forms/Input/AuInput.stories.js
  stories/5-components/Forms/Input/Inputmask.stories.js
  tests/integration/components/au-input-test.js
Labels: enhancement, Deprecation

#432 Resolve `AuInput` deprecations in the `AuTimePicker` component
  addon/components/au-time-picker.hbs
  addon/components/au-time-picker.js
Labels: bug

#433 Deprecate the `tertiary` button skin
  addon/components/au-accordion.hbs
  addon/components/au-button.js
  addon/components/au-card.hbs
  addon/components/au-data-table/number-pagination.hbs
  stories/5-components/Brand/AuMainHeader.stories.js
  stories/5-components/Content/AuCard.stories.js
  stories/5-components/Navigation/AuDropdown.stories.js
  stories/5-components/Tables/AuDataTable.stories.js
  stories/6-patterns/forms.stories.js
  stories/7-templates/AppBreadcrumbs.stories.js
  stories/7-templates/AppEditor.stories.js
  stories/7-templates/AppSidebar.stories.js
  tests/integration/components/au-button-test.js
Labels: enhancement, Deprecation

#434 Deprecate the 2-way-binding setup in the AuToggleSwitch component
  addon/components/au-toggle-switch.js
  stories/5-components/Forms/AuToggleSwitch.stories.js
  tests/integration/components/au-toggle-switch-test.js
Labels: enhancement, Deprecation

#435 Add a `{{au-date-input}}` modifier
  addon/components/au-date-input.hbs
  addon/modifiers/au-date-input.js
  app/modifiers/au-date-input.js
  stories/5-components/Forms/AuDateInput.stories.js
  tests/integration/modifiers/au-date-input-test.js
Labels: enhancement

#437 Deprecate the `AuTextarea` `@value` argument
  addon/components/au-textarea.hbs
  addon/components/au-textarea.js
  stories/5-components/Forms/AuTextarea.stories.js
  tests/integration/components/au-textarea-test.js
Labels: enhancement, Deprecation
