Repository appuniversum/ember-appuniversum, pull requests merged in 2023-02, with the labels that each got.

#366 Use the proper name for the checkbox and radio components in the documentation
  stories/5-components/Forms/AuCheckbox.stories.js
  stories/5-components/Forms/AuRadio.stories.js
Labels: documentation

#364 Add a `<AuDateInput>` component
  addon/components/au-date-input.hbs
  addon/components/au-date-input.js
  addon/components/au-date-picker.js
  addon/utils/date.js
  app/components/au-date-input.js
  app/styles/ember-appuniversum/_c-input.scss
  package-lock.json
  package.json
  stories/5-components/Forms/AuDateInput.stories.js
  tests/integration/components/au-date-input-test.js
Labels: enhancement

#369 Add a `@maskOptions` argument to the AuInput component
  addon/components/au-input.hbs
  addon/components/au-input.js
  package-lock.json
  package.json
  stories/5-components/Forms/AuInput.stories.js
Labels: enhancement

#370 Improve the consistency between the AuControlCheckbox and AuControlRadio components
  addon/components/au-control-radio.hbs
  stories/5-components/Forms/AuFieldset.stories.js
  stories/5-components/Forms/AuRadio.stories.js
  stories/6-patterns/forms.stories.js
Labels: enhancement

#373 Fix the disableWormholeElement exception
  index.js
Labels: bug

#374 Disable the `AuButton` component when it is in the loading state
  addon/components/au-button.hbs
  addon/components/au-button.js
  tests/integration/components/au-button-test.js
Labels: bug

#379 Only call `.focus` if the element exist
  addon/components/au-main-header.js
Labels: bug

#380 Fix a `<AuToggleSwitch>` shrinking issue
  app/styles/ember-appuniversum/_c-toggle-switch.scss
Labels: bug
