Repository appuniversum/ember-appuniversum, pull requests merged in 2024-03, with the labels that each got.

#479 Fix incompatibilities between some `AuModal` arguments
  addon/components/au-modal.gjs
  addon/private/helpers/class-names.ts
  tests/integration/private/helpers/class-names-test.gts
Labels: bug

#481 [Experimental feature] Add support for using components as icons
  addon/components/au-accordion.gts
  addon/components/au-alert.gts
  addon/components/au-badge.gts
  addon/components/au-button.gts
  addon/components/au-card.gts
  addon/components/au-icon.gts
  addon/components/au-input.gts
  addon/components/au-link-external.gts
  addon/components/au-link.gts
  addon/components/au-pill.gts
Labels: enhancement

#487 [Experimental] Add icon components
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  lib/generate-icon-components.mjs
  package-lock.json
  package.json
  tests/integration/components/icon-components-test.gts
Labels: enhancement

#486 Use the icon components internally
  addon/components/au-accordion.gts
  addon/components/au-alert.gts
  addon/components/au-card.gts
  addon/components/au-data-table/number-pagination.hbs
  addon/components/au-data-table/number-pagination.js
  addon/components/au-data-table/text-search.hbs
  addon/components/au-data-table/text-search.js
  addon/components/au-data-table/th-sortable.hbs
  addon/components/au-data-table/th-sortable.js
  addon/components/au-date-input.gts
  addon/components/au-dropdown.gjs
  addon/components/au-fieldset.gts
  addon/components/au-file-card.gts
  addon/components/au-file-upload.gts
  addon/components/au-label.gts
  addon/components/au-main-header.gts
  addon/components/au-modal.gjs
Labels: internal

#488 Remove the fill attribute from all icons
  lib/generate-icon-components.mjs
  public/icons/caret-up-down.svg
  public/icons/eye.svg
  public/icons/github.svg
  public/icons/html-dot.svg
  public/icons/image.svg
  public/icons/link-broken.svg
  public/icons/users-one-of-four.svg
  public/icons/users-three-of-four.svg
  public/icons/users-two-of-four.svg
  public/icons/visible.svg
  public/icons/vote-star-filled.svg
Labels: bug
